### ISSUE TITLE
M value or beta value?

### ISSUE THREAD

**Issue by ggzheng** [lissettegomez/coMethDMR#3]
Hi,

I saw you mentioned that "there are two main steps in coMethDMR: (1) identifying comethylatyed clusters (2) testing methylation levels in those comethylated clusters against a phenotype". 

In step 1 and 2, should we use beta value or M values for CoMethDMR? 

Thanks!

**Comment by ggzheng** [comment]
I double checked documents. I think it should use M values in step 1 and 2.

**Comment by gabrielodom** [comment]
Hi Yuanchao,

**Comment by gabrielodom** [comment]
Hi Yuanchao, please forgive us for taking so long to reply. We are quite busy with grants and the COVID-19 response in our region. It appears that you were able to find an answer, but please do not hesitate to reopen this issue if you get stuck again :)

**Comment by ggzheng** [comment]
No worry. I noticed it uses M values, but the input for step 1 could be either beta or M, but the input for step 2 should be the beta matrix. That's what I found.
