### ISSUE TITLE
WGBS

### ISSUE THREAD

**Issue by yeduo2019** [lissettegomez/coMethDMR#9]
Hi, Gabriel Lodom,
Is it possible to use coMethDMR to analyze genome-wide methylation data?

Best regards 
Yeduo

**Comment by gabrielodom** [comment]
Hi @yeduo2019, we do not monitor the issues in this repo, and we are not in active development of this version of the package. Please download the updated version of this package from our lab GitHub page: https://github.com/TransBioInfoLab/coMethDMR

Also, please copy this issue to our lab-maintained version of the coMethDMR repository here: https://github.com/TransBioInfoLab/coMethDMR/issues
